config/routes.rb
Rails.application.routes.draw do
  resources :years
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  root 'welcome#index'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'login/index'

  resources :insides
  get 'welcome/index'

  resources :insides do
    put :favorite, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/inside.rb
class Inside < ApplicationRecord
  has_and_belongs_to_many :years

  self.per_page = 10
  def self.search(search)
    where("LOWER(name) LIKE ? OR
    LOWER(category) LIKE ? OR
    LOWER(department) LIKE ? ",
    "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%"
    )
  end

  #define filter
  def self.filter(category = nil, department = nil, location = nil, finaid = nil)
    return where(category: category, department: department, location: location, finaid: finaid) if category && department && location && finaid
    return where(finaid: finaid, department: department, location: location) if finaid && department && location
    return where(category: category, finaid: finaid, location: location) if category && finaid && location
    return where(category: category, department: department, finaid: finaid) if category && department && finaid
    return where(category: category, department: department, location: location) if category && department && location
    return where(category: category, location: location) if category && location
    return where(department: department, location: location) if department && location
    return where(category: category, department: department) if category && department
    return where(finaid: finaid, category: category) if finaid && category
    return where(finaid: finaid, location: location) if finaid && location
    return where(finaid: finaid, department: department) if finaid && department
    return where(category: category) if category
    return where(department: department) if department
    return where(location: location) if location
    return where(finaid: finaid) if finaid
    all
  end

  has_many :favorite_insides # just the 'relationships'
  has_many :favorited_by, through: :favorite_insides, source: :user
end

app/controllers/insides_controller.rb
class InsidesController < ApplicationController
  before_action :set_inside, only: [:show, :edit, :update, :destroy]

  # GET /insides
  # GET /insides.json

  def index
    @insides = Inside.paginate(:page => params[:page])

    @current_user = User.find_by id: session[:user_id]
    # some random conditional
    if @current_user.name == "Mario See" or @current_user.name == "Sarah Xu"
      @current_user.update_attribute :admin, true
    end

    ### SEARCHING ###
    if params[:search]
      @insides = Inside.search(params[:search], ).paginate(page: params[:page])
    end

    ### FILTERING ###
    #implementing filter
    if params[:category] or params[:department] or params[:location] or params[:finaid]
      @insides = Inside.filter(params[:category], params[:department], params[:location], params[:finaid]).paginate(page: params[:page])
    end

    ###    SORTING   ###
    # Sorts all recipes based on the selected sorting column
    if params[:sorting] == 'name'
      #SQL syntax is used here, replace ASC with DESC if you want reverse order
      @insides = @insides.filter(params[:category], params[:department], params[:location], params[:finaid] ).order('insides.name ASC').paginate(page: params[:page])
    elsif params[:sorting] == 'category'
      @insides = @insides.filter(params[:category], params[:department], params[:location], params[:finaid]).order('insides.category ASC').paginate(page: params[:page])

    elsif params[:sorting] == 'department'
      @insides = @insides.filter(params[:category], params[:department], params[:location], params[:finaid]).order('insides.department ASC').paginate(page: params[:page])

    elsif params[:sorting] == 'deadline'
      @insides = @insides.filter(params[:category], params[:department], params[:location], params[:finaid]).order('insides.deadline ASC').paginate(page: params[:page])
    end

  end

  def favorite
    type = params[:type]
    @inside = Inside.find params[:id]
    if type == "favorite"
      current_user.favorites << @inside
      redirect_to :back, notice: 'You favorited #{@inside.name}'

    elsif type == "unfavorite"
      current_user.favorites.delete(@inside)
      redirect_to :back, notice: 'Unfavorited #{@inside.name}'

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end

  # GET /insides/1
  # GET /insides/1.json
  def show
  end

  # GET /insides/new
  def new
    @inside = Inside.new
  end

  # GET /insides/1/edit
  def edit
  end

  # POST /insides
  # POST /insides.json
  def create
    @inside = Inside.new(inside_params)
    #params.require(:inside).permit(:year, year_ids:[])
    respond_to do |format|
      if @inside.save
        format.html { redirect_to @inside, notice: 'Inside was successfully created.' }
        format.json { render :show, status: :created, location: @inside }
      else
        format.html { render :new }
        format.json { render json: @inside.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insides/1
  # PATCH/PUT /insides/1.json
  def update
    respond_to do |format|
      if @inside.update(inside_params)
        format.html { redirect_to @inside, notice: 'Inside was successfully updated.' }
        format.json { render :show, status: :ok, location: @inside }
      else
        format.html { render :edit }
        format.json { render json: @inside.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insides/1
  # DELETE /insides/1.json
  def destroy
    @inside.destroy
    respond_to do |format|
      format.html { redirect_to insides_url, notice: 'Inside was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inside
      @inside = Inside.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inside_params
      params.require(:inside).permit(:name, :deadline, :category, :link, :year, :description , :department, :location, :finaid, year_ids:[])
    end

end

app/helpers/insides_helper.rb
module InsidesHelper
end

app/views/insides/_form.html.erb
<%= form_for(inside) do |f| %>
  <% if inside.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inside.errors.count, "error") %> prohibited this inside from being saved:</h2>

      <ul>
      <% inside.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :required => true  %>
  </div>

  <div class="field">
    <%= f.label :deadline %>
    <%= f.date_select :deadline, :required => true  %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.select :category, ['Fellowship', 'Entrepreneurship', 'Scholarship', 'Grant', 'Research'], :required => true %>
  </div>

  <div class="field">
    <%= f.label :department %>
    <%= f.select :department, ['African American Studies', 'African Studies', 'American Studies', 'English', 'CIS'], :required => true %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :required => true %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.select :location, ['On-Campus', 'Off-Campus'],:required => true  %>
  </div>

  <div class="field">
    <%= f.label "Financial aid eligibility required?" %>
    <%= f.select :finaid, ['Aid required', 'Aid not required'],:required => true  %>
  </div>

  <div class="field">
    <%= f.label "Years Eligible:" %><br />
    <%= f.collection_check_boxes :year_ids, Year.all, :id, :year do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link, :required => true  %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insides/edit.html.erb
<h1>Editing Inside</h1>

<%= render 'form', inside: @inside %>

<%= link_to 'Show', @inside %> |
<%= link_to 'Back', insides_path %>

app/views/insides/new.html.erb
<h1>New Inside</h1>

<%= render 'form', inside: @inside %>

<%= link_to 'Back', insides_path %>

app/views/insides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inside.name %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @inside.deadline %>
</p>

<p>
  <strong>Category:</strong>
  <%= @inside.category %>
</p>

<p>
  <strong>Department:</strong>
  <%= @inside.department %>
</p>

<p>
  <strong>Description:</strong>
  <%= @inside.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= link_to "Click here to apply", @inside.link, :target => "_blank" %>

</p>


<%= link_to 'Edit', edit_inside_path(@inside) %> |
<%= link_to 'Back', insides_path %>